#!/bin/sh /etc/rc.common
#
# mcu_oled version 1.1 by pekmop1024
#
# GL.inet GL-E750 MCU OLED script for vanilla OpenWrt
#
# License:
#  * GPL3 (https://www.gnu.org/licenses/gpl-3.0.en.html)

START=21
STOP=9
USE_PROCD=1

boot() {
    echo 1 4 1 7 > /proc/sys/kernel/printk
    /bin/stty -F /dev/ttyS0 115200 min 0 time 1 ignbrk -brkint -icrnl -imaxbel -opost -olcuc -ocrnl -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke
    echo "{OK}" > /dev/ttyS0
    sleep 1s
    echo "{ \"mcu_status\": \"0\", \"custom_en\": \"1\", \"content\": \" please wait... \", \"display_mask\": \"0\" }" > /dev/ttyS0
    touch /var/run/mcu_init.state
    sleep 1s
    start
}

shutdown() {
    echo "{OK}" > /dev/ttyS0
    echo "{ \"mcu_status\": \"0\", \"custom_en\": \"1\", \"content\": \" please wait... \", \"display_mask\": \"0\" }" > /dev/ttyS0
    echo "{ \"system\": \"reboot\" }" > /dev/ttyS0
    stop
}

start_service() {
    if [[ ! -e /etc/config/mcu_oled ]]; then
        logger -p daemon.error -t "mcu_oled" "missing config /etc/config/mcu_oled!"
        return 1
    fi
    config_load "mcu_oled"
    logger -p daemon.notice -t "mcu_oled" "starting mcu_oled ..."
    procd_open_instance
    procd_set_param command /usr/bin/mcu_oled
    procd_set_param file /etc/config/mcu_oled
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "mcu_oled"
}

reload_service() {
    logger -p daemon.notice -t "mcu_oled" "restarting mcu_oled ..."
    stop
    start
}
